### PR TITLE
non-recursive make and fix build

### PR DESCRIPTION
**Pull request by mbkma**
This should fix all remaining issues with pluma-plugins. Building and `make distcheck` now works for me. I basically checked out at a more recent commit of gedit-plugins, this is why po files have also changed.
I still dont have the greatest knowledge when it comes to autotools, which is why I would be grateful if someone could verify that building pluma-plugins works now.

### CODE REVIEW

**Comment by raveit65** [comment]
Weird, i am missing `Makefile.in` and `Makefile` in plugin dirs after compiling.
```
[rave@mother pluma-plugins-dist]$ ls -l plugins/codecomment/
insgesamt 44
-rw-rw-r-- 1 rave rave 7445 10. Nov 21:16 codecomment.plugin
-rw-rw-r-- 1 rave rave  339 10. Nov 21:15 codecomment.plugin.desktop.in
-rw-rw-r-- 1 rave rave  342 10. Nov 21:04 codecomment.plugin.desktop.in.in
-rw-rw-r-- 1 rave rave 9890 10. Nov 21:02 codecomment.py
-rw-rw-r-- 1 rave rave  380 10. Nov 21:04 Makefile.am
-rw-rw-r-- 1 rave rave 5475 10. Nov 21:16 pluma-codecomment.metainfo.xml
-rw-rw-r-- 1 rave rave  594 10. Nov 21:04 pluma-codecomment.metainfo.xml.in
[rave@mother pluma-plugins-dist]$ ls -l plugins/synctex/
insgesamt 32
-rw-rw-r-- 1 rave rave  485 10. Nov 21:04 Makefile.am
-rw-rw-r-- 1 rave rave 5475 10. Nov 21:16 pluma-synctex.metainfo.xml
-rw-rw-r-- 1 rave rave  658 10. Nov 21:04 pluma-synctex.metainfo.xml.in
drwxrwxr-x 2 rave rave 4096 10. Nov 21:04 synctex
-rw-rw-r-- 1 rave rave  980 10. Nov 21:16 synctex.plugin
-rw-rw-r-- 1 rave rave  280 10. Nov 21:15 synctex.plugin.desktop.in
-rw-rw-r-- 1 rave rave  283 10. Nov 21:04 synctex.plugin.desktop.in.in
[rave@mother pluma-plugins-dist]$ ls -l plugins/terminal/
insgesamt 52
-rw-rw-r-- 1 rave rave   479 10. Nov 21:04 Makefile.am
-rw-rw-r-- 1 rave rave     0 10. Nov 21:16 org.mate.pluma.plugins.terminal.gschema.valid
-rw-rw-r-- 1 rave rave  5634 10. Nov 21:04 org.mate.pluma.plugins.terminal.gschema.xml
-rw-rw-r-- 1 rave rave  5475 10. Nov 21:16 pluma-terminal.metainfo.xml
-rw-rw-r-- 1 rave rave   609 10. Nov 21:04 pluma-terminal.metainfo.xml.in
-rw-rw-r-- 1 rave rave  4167 10. Nov 21:16 terminal.plugin
-rw-rw-r-- 1 rave rave   344 10. Nov 21:15 terminal.plugin.desktop.in
-rw-rw-r-- 1 rave rave   347 10. Nov 21:04 terminal.plugin.desktop.in.in
-rw-rw-r-- 1 rave rave 12245 10. Nov 21:02 terminal.py
```
Are the plugins built?

```
[rave@mother pluma-plugins-dist]$ ./autogen.sh 
autoreconf: Entering directory `.'

<cut>

config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile


Configuration:

	Source code location:   .
	Compiler:               gcc
	Prefix:                 /usr
	Python Plugins Support: yes

	Plugins:
	   codecomment synctex terminal

	Disabled plugins:
	  

Note: you have to install these plugins into the same prefix as your pluma
installation (probably /usr if you're using your distro packages, /usr/local
if you have compiled it on your own).

[rave@mother pluma-plugins-dist]$ make
make  all-recursive
make[1]: Entering directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/pluma-plugins-dist'
Making all in help
make[2]: Entering directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/pluma-plugins-dist/help'
  GEN      ar/ar.mo
  GEN    ar/

<cut>

  GEN      zh_TW/zh_TW.mo
  GEN    zh_TW/
make[2]: Leaving directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/pluma-plugins-dist/help'
Making all in po
make[2]: Entering directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/pluma-plugins-dist/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/pluma-plugins-dist/po'
make[2]: Entering directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/pluma-plugins-dist'
  GEN      plugins/codecomment/pluma-codecomment.metainfo.xml
  GEN      plugins/synctex/pluma-synctex.metainfo.xml
  GEN      plugins/terminal/pluma-terminal.metainfo.xml
  GEN      plugins/codecomment/codecomment.plugin
  GEN      plugins/synctex/synctex.plugin
  GEN      plugins/terminal/terminal.plugin
  GEN      plugins/terminal/org.mate.pluma.plugins.terminal.gschema.valid
make[2]: Leaving directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/pluma-plugins-dist'
make[1]: Leaving directory '/media/Data/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/pluma-plugins-dist'
[rave@mother pluma-plugins-dist]$ 
```

**Comment by raveit65** [comment]
At python plugins of pluma there is always a `__init__.py` file in folders, maybe that is missing?
I am also not very good with creating make file for autotools.
@mate-desktop/core-team @rbuj @vkareh 
Any idea?

But why not using meson build system for a new package?
Then you take a look at gedit-plugins how it works ;)
https://gitlab.gnome.org/GNOME/gedit-plugins/-/tree/master/plugins

**Comment by rbuj** [comment]
@mbkma you can modify the po files in another commit, in order to make it easier to track the changesets.

**Comment by rbuj** [comment]
I prefer to use subdirs as it is more versatile than defining variables for including them in a generic makefile

**Comment by mbkma** [comment]
see #3

**Comment by raveit65** [comment]
I had to duplicate the repo to pluma-plugins-new and we will last old PRs from here.
But i think this is OK.
https://github.com/mate-desktop/pluma-plugins-new
@mbkma @rbuj 
Can you please check the new repo?
Than i will delete this one and rename the new one.

**Comment by mbkma** [comment]
new repo seems good: test: `diff -qr pluma-plugins-new/ pluma-plugins/` ; builds and runs fine.

**Pull request closed without merging**
