### PR TITLE
add sourcecodebrowser plugin

### PR DESCRIPTION
**Pull request by mbkma**
This is a fork of the no longer maintained Gedit Source Code Browser https://github.com/MicahCarrick/gedit-source-code-browser
I don't know if @MicahCarrick is okay with including it here under the GPL-2.0 License, so I used the original license.
Screenshot at 2021-03-06 11-13-38

I think a condition in configure.ac for the `exuberant-ctags` dependency is needed, but 
```
	PKG_CHECK_MODULES([EXCTAGS],
		[ectags >= $EXCTAGS_REQUIRED],
		[have_ectags=yes],
		[have_ectags=no])
```
does not seem to find it.

### CODE REVIEW

**Comment by rbuj** [comment]
@mbkma `ctags` is a binary application, it's not a library, so you don't need to get link/compilation flags. You only need to add a runtime dependency when building the package.

There is no need to override the path to `ctags` because you can set it in the plugin preferences, and using AC_PATH_PROG isn't recommended because of fakeroot or other virtualenvs used for building packages.

**Comment by rbuj** [comment]
It seems [gedit-source-code-browser](https://github.com/MicahCarrick/gedit-source-code-browser) is licensed under [The 3-Clause BSD License](https://directory.fsf.org/wiki/License:BSD-3-Clause) which is Free and GPL-Compatible License.

**Review by rbuj — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
@mbkma 
Oh, there is a merge conflict with master.

**Review by raveit65 — APPROVED** [review]
Works fine

**Pull request merged**
