### PR TITLE
add bookmarks plugin

### PR DESCRIPTION
**Pull request by mbkma**
Bookmarks are enabled from menu or by pressing ctrl+alt+b. Backport from gedit-plugins.

### CODE REVIEW

**Comment by rbuj** [comment]
[file.patch.gz](https://github.com/mate-desktop/pluma-plugins/files/5565930/file.patch.gz)
```diff
diff --git a/plugins/bookmarks/Makefile.am b/plugins/bookmarks/Makefile.am
index fa77712..80cdbc8 100644
--- a/plugins/bookmarks/Makefile.am
+++ b/plugins/bookmarks/Makefile.am
@@ -2,14 +2,14 @@
 plugindir = $(PLUMA_PLUGINS_LIBS_DIR)
 
 AM_CPPFLAGS = \
-	-I$(top_srcdir) 				\
-	$(PLUMA_CFLAGS) 				\
+	-I$(top_srcdir) \
+	$(PLUMA_CFLAGS) \
 	$(WARN_CFLAGS)
 
 plugin_LTLIBRARIES = libbookmarks.la
 
 libbookmarks_la_SOURCES = \
-	pluma-bookmarks-plugin.c				\
+	pluma-bookmarks-plugin.c \
 	pluma-bookmarks-plugin.h
 
 libbookmarks_la_LDFLAGS = $(PLUGIN_LIBTOOL_FLAGS)
@@ -29,10 +29,15 @@ $(metainfo_DATA): $(metainfo_in_files)
 	$(AM_V_GEN) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
 
 EXTRA_DIST = \
-	$(plugin_in_files)				\
-	$(bookmarks_DATA)
+	$(plugin_in_files) \
+	$(metainfo_in_files)
 
-CLEANFILES = $(plugin_DATA)
-DISTCLEANFILES = $(plugin_DATA)
+CLEANFILES = \
+	$(plugin_DATA) \
+	$(metainfo_DATA)
+
+DISTCLEANFILES = \
+	$(metainfo_DATA) \
+	$(plugin_DATA)
 
 -include $(top_srcdir)/git.mk
diff --git a/plugins/bookmarks/pluma-bookmarks-plugin.c b/plugins/bookmarks/pluma-bookmarks-plugin.c
index c71bed6..64dce6a 100644
--- a/plugins/bookmarks/pluma-bookmarks-plugin.c
+++ b/plugins/bookmarks/pluma-bookmarks-plugin.c
@@ -47,19 +47,19 @@
 
 typedef struct
 {
-	GtkSourceMark *bookmark;
-	GtkTextMark *mark;
+	GtkSourceMark  *bookmark;
+	GtkTextMark    *mark;
 } InsertTracker;
 
 typedef struct
 {
-	GSList *trackers;
-	guint user_action;
+	GSList  *trackers;
+	guint    user_action;
 } InsertData;
 
 static void on_style_scheme_notify		(GObject     *object,
-						 GParamSpec  *pspec,
-						 PlumaView   *view);
+                                                 GParamSpec  *pspec,
+                                                 PlumaView   *view);
 
 static void on_delete_range			(GtkTextBuffer *buffer,
 						 GtkTextIter   *start,
@@ -67,31 +67,31 @@ static void on_delete_range			(GtkTextBuffer *buffer,
 						 gpointer       user_data);
 
 static void on_insert_text_before		(GtkTextBuffer *buffer,
-						 GtkTextIter   *location,
-						 gchar         *text,
-						 gint		len,
-						 InsertData    *data);
+                                                 GtkTextIter   *location,
+                                                 gchar         *text,
+                                                 gint		len,
+                                                 InsertData    *data);
 
 static void on_begin_user_action		(GtkTextBuffer *buffer,
-						 InsertData    *data);
+                                                 InsertData    *data);
 
-static void on_end_user_action			(GtkTextBuffer *buffer,
-						 InsertData    *data);
+static void on_end_user_action                  (GtkTextBuffer *buffer,
+                                                 InsertData    *data);
 
-static void on_toggle_bookmark_activate 	(GtkAction            *action,
-						 PlumaBookmarksPlugin *plugin);
-static void on_next_bookmark_activate 		(GtkAction            *action,
-						 PlumaBookmarksPlugin *plugin);
+static void on_toggle_bookmark_activate         (GtkAction            *action,
+                                                 PlumaBookmarksPlugin *plugin);
+static void on_next_bookmark_activate           (GtkAction            *action,
+                                                 PlumaBookmarksPlugin *plugin);
 static void on_previous_bookmark_activate 	(GtkAction            *action,
-						 PlumaBookmarksPlugin *plugin);
+                                                 PlumaBookmarksPlugin *plugin);
 static void on_tab_added 			(PlumaWindow          *window,
-						 PlumaTab             *tab,
-						 PlumaBookmarksPlugin *plugin);
+                                                 PlumaTab             *tab,
+                                                 PlumaBookmarksPlugin *plugin);
 static void on_tab_removed 			(PlumaWindow          *window,
-						 PlumaTab             *tab,
-						 PlumaBookmarksPlugin *plugin);
+                                                 PlumaTab             *tab,
+                                                 PlumaBookmarksPlugin *plugin);
 
-static void add_bookmark (GtkSourceBuffer *buffer, GtkTextIter *iter);
+static void add_bookmark    (GtkSourceBuffer *buffer, GtkTextIter *iter);
 static void remove_bookmark (GtkSourceBuffer *buffer, GtkTextIter *iter);
 static void toggle_bookmark (GtkSourceBuffer *buffer, GtkTextIter *iter);
 
@@ -99,10 +99,10 @@ static void peas_activatable_iface_init (PeasActivatableInterface *iface);
 
 struct _PlumaBookmarksPluginPrivate
 {
-	PlumaWindow *window;
+	PlumaWindow     *window;
 
-	GtkActionGroup *action_group;
-	guint ui_id;
+	GtkActionGroup  *action_group;
+	guint            ui_id;
 };
 
 G_DEFINE_DYNAMIC_TYPE_EXTENDED (PlumaBookmarksPlugin,
@@ -224,11 +224,10 @@ static void
 install_menu (PlumaBookmarksPlugin *plugin)
 {
 	PlumaBookmarksPluginPrivate *priv;
-	GtkUIManager *manager;
-	GError *error = NULL;
+	GtkUIManager                *manager;
+	GError                      *error = NULL;
 
 	priv = plugin->priv;
-
 	manager = pluma_window_get_ui_manager (priv->window);
 	priv->action_group = gtk_action_group_new ("PlumaBookmarksPluginActions");
 
@@ -254,10 +253,9 @@ static void
 uninstall_menu (PlumaBookmarksPlugin *plugin)
 {
 	PlumaBookmarksPluginPrivate *priv;
-	GtkUIManager *manager;
+	GtkUIManager                *manager;
 
 	priv = plugin->priv;
-
 	manager = pluma_window_get_ui_manager (priv->window);
 
 	gtk_ui_manager_remove_ui (manager, priv->ui_id);
@@ -307,8 +305,8 @@ static GdkPixbuf *
 get_bookmark_pixbuf (PlumaBookmarksPlugin *plugin)
 {
 	GdkPixbuf *pixbuf;
-	gint width;
-	GError *error = NULL;
+	gint       width;
+	GError    *error = NULL;
 
 	gtk_icon_size_lookup (GTK_ICON_SIZE_MENU, &width, NULL);
 	pixbuf = gtk_icon_theme_load_icon (gtk_icon_theme_get_default (),
@@ -328,10 +326,11 @@ get_bookmark_pixbuf (PlumaBookmarksPlugin *plugin)
 }
 
 static void
-update_background_color (GtkSourceMarkAttributes *attrs, GtkSourceBuffer *buffer)
+update_background_color (GtkSourceMarkAttributes *attrs,
+                         GtkSourceBuffer         *buffer)
 {
 	GtkSourceStyleScheme *scheme;
-	GtkSourceStyle *style;
+	GtkSourceStyle       *style;
 
 	scheme = gtk_source_buffer_get_style_scheme (buffer);
 	style = gtk_source_style_scheme_get_style (scheme, "search-match");
@@ -360,7 +359,7 @@ update_background_color (GtkSourceMarkAttributes *attrs, GtkSourceBuffer *buffer
 
 static void
 enable_bookmarks (PlumaView            *view,
-		  PlumaBookmarksPlugin *plugin)
+                  PlumaBookmarksPlugin *plugin)
 {
 	GdkPixbuf *pixbuf;
 
@@ -428,13 +427,13 @@ enable_bookmarks (PlumaView            *view,
 }
 
 static void
-load_bookmarks (PlumaView *view,
-		gchar    **bookmarks)
+load_bookmarks (PlumaView  *view,
+                gchar     **bookmarks)
 {
 	GtkSourceBuffer *buf;
-	GtkTextIter iter;
-	gint tot_lines;
-	gint i;
+	GtkTextIter      iter;
+	gint             tot_lines;
+	gint             i;
 
 	pluma_debug (DEBUG_PLUGINS);
 
@@ -458,19 +457,14 @@ load_bookmarks (PlumaView *view,
 
 			marks = gtk_source_buffer_get_source_marks_at_iter (buf, &iter,
 									    BOOKMARK_CATEGORY);
-
 			if (marks == NULL)
-			{
 				/* Add new bookmark */
 				gtk_source_buffer_create_source_mark (buf,
 								      NULL,
 								      BOOKMARK_CATEGORY,
 								      &iter);
-			}
 			else
-			{
 				g_slist_free (marks);
-			}
 		}
 	}
 }
@@ -479,7 +473,7 @@ static void
 load_bookmark_metadata (PlumaView *view)
 {
 	PlumaDocument *doc;
-	gchar *bookmarks_attr;
+	gchar         *bookmarks_attr;
 
 	doc = PLUMA_DOCUMENT (gtk_text_view_get_buffer (GTK_TEXT_VIEW (view)));
 	bookmarks_attr = pluma_document_get_metadata (doc, METADATA_ATTR);
@@ -504,35 +498,26 @@ static void
 goto_bookmark (PlumaWindow    *window,
                GtkSourceView  *view,
                GtkTextIter    *iter,
-	       IterSearchFunc  func,
-	       CycleFunc       cycle_func)
+               IterSearchFunc  func,
+               CycleFunc       cycle_func)
 {
 	GtkTextBuffer *buffer;
-	GtkTextIter at;
-	GtkTextIter end;
+	GtkTextIter    at;
+	GtkTextIter    end;
 
 	if (view == NULL)
-	{
 		view = GTK_SOURCE_VIEW (pluma_window_get_active_view (window));
-	}
 
-	if (view == NULL)
-	{
-		return;
-	}
+	g_return_if_fail (view != NULL);
 
 	buffer = gtk_text_view_get_buffer (GTK_TEXT_VIEW (view));
 
 	if (iter == NULL)
-	{
 		gtk_text_buffer_get_iter_at_mark (buffer,
 		                                  &at,
 		                                  gtk_text_buffer_get_insert (buffer));
-	}
 	else
-	{
 		at = *iter;
-	}
 
 	/* Move the iter to the beginning of the line, where the bookmarks are */
 	gtk_text_iter_set_line_offset (&at, 0);
@@ -551,23 +536,16 @@ goto_bookmark (PlumaWindow    *window,
 		                                                    BOOKMARK_CATEGORY);
 
 		if (!marks && !func (GTK_SOURCE_BUFFER (buffer), &at, BOOKMARK_CATEGORY))
-		{
 			return;
-		}
 
 		g_slist_free (marks);
 	}
 
 	end = at;
-
 	if (!gtk_text_iter_forward_visible_line (&end))
-	{
 		gtk_text_buffer_get_end_iter (buffer, &end);
-	}
 	else
-	{
 		gtk_text_iter_backward_char (&end);
-	}
 
 	gtk_text_buffer_select_range (buffer, &at, &end);
 	gtk_text_view_scroll_to_iter (GTK_TEXT_VIEW (view), &at, 0.3, FALSE, 0, 0);
@@ -580,18 +558,11 @@ message_get_view_iter (PlumaWindow    *window,
                        GtkTextIter    *iter)
 {
 	if (pluma_message_has_key (message, "view"))
-	{
 		pluma_message_get (message, "view", view, NULL);
-	}
 	else
-	{
 		*view = GTK_SOURCE_VIEW (pluma_window_get_active_view (window));
-	}
 
-	if (!*view)
-	{
-		return;
-	}
+	g_return_if_fail (*view);
 
 	if (pluma_message_has_key (message, "iter"))
 	{
@@ -616,10 +587,7 @@ message_toggle_cb (PlumaMessageBus *bus,
 
 	message_get_view_iter (window, message, &view, &iter);
 
-	if (!view)
-	{
-		return;
-	}
+	g_return_if_fail (view);
 
 	toggle_bookmark (GTK_SOURCE_BUFFER (gtk_text_view_get_buffer (GTK_TEXT_VIEW (view))),
 	                 &iter);
@@ -635,10 +603,7 @@ message_add_cb (PlumaMessageBus *bus,
 
 	message_get_view_iter (window, message, &view, &iter);
 
-	if (!view)
-	{
-		return;
-	}
+	g_return_if_fail (view);
 
 	add_bookmark (GTK_SOURCE_BUFFER (gtk_text_view_get_buffer (GTK_TEXT_VIEW (view))),
 	              &iter);
@@ -654,10 +619,7 @@ message_remove_cb (PlumaMessageBus *bus,
 
 	message_get_view_iter (window, message, &view, &iter);
 
-	if (!view)
-	{
-		return;
-	}
+	g_return_if_fail (view);
 
 	remove_bookmark (GTK_SOURCE_BUFFER (gtk_text_view_get_buffer (GTK_TEXT_VIEW (view))),
 	                 &iter);
@@ -673,10 +635,7 @@ message_goto_next_cb (PlumaMessageBus *bus,
 
 	message_get_view_iter (window, message, &view, &iter);
 
-	if (!view)
-	{
-		return;
-	}
+	g_return_if_fail (view);
 
 	goto_bookmark (window,
 	               view,
@@ -695,10 +654,7 @@ message_goto_previous_cb (PlumaMessageBus *bus,
 
 	message_get_view_iter (window, message, &view, &iter);
 
-	if (!view)
-	{
-		return;
-	}
+	g_return_if_fail (view);
 
 	goto_bookmark (window,
 	               view,
@@ -810,16 +766,14 @@ pluma_bookmarks_plugin_update_state (PeasActivatable *activatable)
 static void
 save_bookmark_metadata (PlumaView *view)
 {
-	GtkTextIter iter;
+	GtkTextIter    iter;
 	GtkTextBuffer *buf;
-	GString *string;
-	gchar *val = NULL;
-	gboolean first = TRUE;
+	GString       *string;
+	gchar         *val = NULL;
+	gboolean       first = TRUE;
 
 	buf = gtk_text_view_get_buffer (GTK_TEXT_VIEW (view));
-
 	gtk_text_buffer_get_start_iter (buf, &iter);
-
 	string = g_string_new (NULL);
 
 	while (gtk_source_buffer_forward_iter_to_source_mark (GTK_SOURCE_BUFFER (buf),
@@ -847,7 +801,9 @@ save_bookmark_metadata (PlumaView *view)
 		val = NULL;
 	}
 	else
+	{
 		val = g_string_free (string, FALSE);
+	}
 
 	pluma_document_set_metadata (PLUMA_DOCUMENT (buf), METADATA_ATTR,
 				     val, NULL);
@@ -872,9 +828,7 @@ pluma_bookmarks_plugin_deactivate (PeasActivatable *activatable)
 	views = pluma_window_get_views (priv->window);
 
 	for (item = views; item != NULL; item = item->next)
-	{
 		disable_bookmarks (PLUMA_VIEW (item->data));
-	}
 
 	g_list_free (views);
 
@@ -887,7 +841,7 @@ pluma_bookmarks_plugin_class_init (PlumaBookmarksPluginClass *klass)
 {
 	GObjectClass *object_class = G_OBJECT_CLASS (klass);
 
-	object_class->dispose = pluma_bookmarks_plugin_dispose;
+	object_class->dispose      = pluma_bookmarks_plugin_dispose;
 	object_class->set_property = pluma_bookmarks_plugin_set_property;
 	object_class->get_property = pluma_bookmarks_plugin_get_property;
 
@@ -915,9 +869,9 @@ on_style_scheme_notify (GObject     *object,
 
 static void
 on_delete_range (GtkTextBuffer *buffer,
-		 GtkTextIter   *start,
-		 GtkTextIter   *end,
-		 gpointer       user_data)
+                 GtkTextIter   *start,
+                 GtkTextIter   *end,
+                 gpointer       user_data)
 {
 	GtkTextIter start_iter;
 	GtkTextIter end_iter;
@@ -926,9 +880,7 @@ on_delete_range (GtkTextBuffer *buffer,
 	/* Nothing to do for us here. The bookmark, if any, will stay at the
 	   beginning of the line due to its left gravity. */
 	if (gtk_text_iter_get_line (start) == gtk_text_iter_get_line (end))
-	{
 		return;
-	}
 
 	start_iter = *start;
 	gtk_text_iter_set_line_offset (&start_iter, 0);
@@ -950,12 +902,10 @@ on_delete_range (GtkTextBuffer *buffer,
 					       BOOKMARK_CATEGORY);
 
 	if (keep_bookmark)
-	{
 		gtk_source_buffer_create_source_mark (GTK_SOURCE_BUFFER (buffer),
 						      NULL,
 						      BOOKMARK_CATEGORY,
 						      &start_iter);
-	}
 }
 
 static void
@@ -972,9 +922,7 @@ on_end_user_action (GtkTextBuffer *buffer,
 	GSList *item;
 
 	if (--data->user_action > 0)
-	{
 		return;
-	}
 
 	/* Remove trackers */
 	for (item = data->trackers; item; item = g_slist_next (item))
@@ -1022,9 +970,7 @@ add_tracker (GtkTextBuffer *buffer,
 		tracker = item->data;
 
 		if (tracker->bookmark == bookmark)
-		{
 			return;
-		}
 	}
 
 	tracker = g_slice_new (InsertTracker);
@@ -1064,30 +1010,21 @@ get_bookmark_and_iter (GtkSourceBuffer *buffer,
                        GtkTextIter     *iter,
                        GtkTextIter     *start)
 {
-	GSList *marks;
+	GSList        *marks;
 	GtkSourceMark *ret = NULL;
 
 	if (!iter)
-	{
 		gtk_text_buffer_get_iter_at_mark (GTK_TEXT_BUFFER (buffer),
 		                                  start,
 		                                  gtk_text_buffer_get_insert (GTK_TEXT_BUFFER (buffer)));
-	}
 	else
-	{
 		*start = *iter;
-	}
 
 	gtk_text_iter_set_line_offset (start, 0);
 
-	marks = gtk_source_buffer_get_source_marks_at_iter (buffer,
-							    start,
-							    BOOKMARK_CATEGORY);
-
+	marks = gtk_source_buffer_get_source_marks_at_iter (buffer, start, BOOKMARK_CATEGORY);
 	if (marks != NULL)
-	{
 		ret = GTK_SOURCE_MARK (marks->data);
-	}
 
 	g_slist_free (marks);
 	return ret;
@@ -1097,74 +1034,54 @@ static void
 remove_bookmark (GtkSourceBuffer *buffer,
                  GtkTextIter     *iter)
 {
-	GtkTextIter start;
+	GtkTextIter    start;
 	GtkSourceMark *bookmark;
 
-	bookmark = get_bookmark_and_iter (buffer, iter, &start);
-
-	if (bookmark != NULL)
-	{
+	if ((bookmark = get_bookmark_and_iter (buffer, iter, &start)) != NULL)
 		gtk_text_buffer_delete_mark (GTK_TEXT_BUFFER (buffer),
 		                             GTK_TEXT_MARK (bookmark));
-	}
 }
 
 static void
 add_bookmark (GtkSourceBuffer *buffer,
               GtkTextIter     *iter)
 {
-	GtkTextIter start;
+	GtkTextIter    start;
 	GtkSourceMark *bookmark;
 
-	bookmark = get_bookmark_and_iter (buffer, iter, &start);
-
-	if (bookmark == NULL)
-	{
+	if ((bookmark = get_bookmark_and_iter (buffer, iter, &start)) == NULL)
 		gtk_source_buffer_create_source_mark (GTK_SOURCE_BUFFER (buffer),
 						      NULL,
 						      BOOKMARK_CATEGORY,
 						      &start);
-	}
 }
 
 static void
 toggle_bookmark (GtkSourceBuffer *buffer,
                  GtkTextIter     *iter)
 {
-	GtkTextIter start;
+	GtkTextIter    start;
 	GtkSourceMark *bookmark = NULL;
 
-	if (buffer == NULL)
-	{
-		return;
-	}
-
-	bookmark = get_bookmark_and_iter (buffer, iter, &start);
+	g_return_if_fail (buffer != NULL);
 
-	if (bookmark != NULL)
-	{
+	if ((bookmark = get_bookmark_and_iter (buffer, iter, &start)) != NULL)
 		remove_bookmark (buffer, &start);
-	}
 	else
-	{
 		add_bookmark (buffer, &start);
-	}
 }
 
 static void
 on_toggle_bookmark_activate (GtkAction            *action,
-			     PlumaBookmarksPlugin *plugin)
+                             PlumaBookmarksPlugin *plugin)
 {
-	GtkSourceBuffer *buffer;
-
-	buffer = GTK_SOURCE_BUFFER (pluma_window_get_active_document (plugin->priv->window));
-
-	toggle_bookmark (buffer, NULL);
+	toggle_bookmark (GTK_SOURCE_BUFFER (pluma_window_get_active_document (plugin->priv->window)),
+	                 NULL);
 }
 
 static void
 on_next_bookmark_activate (GtkAction            *action,
-			   PlumaBookmarksPlugin *plugin)
+                          PlumaBookmarksPlugin *plugin)
 {
 	goto_bookmark (plugin->priv->window,
 	               NULL,
@@ -1175,7 +1092,7 @@ on_next_bookmark_activate (GtkAction            *action,
 
 static void
 on_previous_bookmark_activate (GtkAction            *action,
-			       PlumaBookmarksPlugin *plugin)
+                               PlumaBookmarksPlugin *plugin)
 {
 	goto_bookmark (plugin->priv->window,
 	               NULL,
@@ -1186,8 +1103,8 @@ on_previous_bookmark_activate (GtkAction            *action,
 
 static void
 on_document_loaded (PlumaDocument *doc,
-		    const GError  *error,
-		    PlumaView     *view)
+                    const GError  *error,
+                    PlumaView     *view)
 {
 	if (error == NULL)
 	{
@@ -1200,24 +1117,22 @@ on_document_loaded (PlumaDocument *doc,
 
 static void
 on_document_saved (PlumaDocument *doc,
-		   const GError  *error,
-		   PlumaView     *view)
+                   const GError  *error,
+                   PlumaView     *view)
 {
 	if (error == NULL)
-	{
 		save_bookmark_metadata (view);
-	}
 }
 
 static void
 on_tab_added (PlumaWindow          *window,
-	      PlumaTab             *tab,
-	      PlumaBookmarksPlugin *plugin)
+              PlumaTab             *tab,
+              PlumaBookmarksPlugin *plugin)
 {
 	PlumaDocument *doc;
-	PlumaView *view;
+	PlumaView     *view;
 
-	doc = pluma_tab_get_document (tab);
+	doc  = pluma_tab_get_document (tab);
 	view = pluma_tab_get_view (tab);
 
 	g_signal_connect (doc, "loaded",
@@ -1232,13 +1147,13 @@ on_tab_added (PlumaWindow          *window,
 
 static void
 on_tab_removed (PlumaWindow          *window,
-	        PlumaTab             *tab,
-	        PlumaBookmarksPlugin *plugin)
+                PlumaTab             *tab,
+                PlumaBookmarksPlugin *plugin)
 {
 	PlumaDocument *doc;
-	PlumaView *view;
+	PlumaView     *view;
 
-	doc = pluma_tab_get_document (tab);
+	doc  = pluma_tab_get_document (tab);
 	view = pluma_tab_get_view (tab);
 
 	g_signal_handlers_disconnect_by_func (doc, on_document_loaded, view);
@@ -1250,8 +1165,8 @@ on_tab_removed (PlumaWindow          *window,
 static void
 peas_activatable_iface_init (PeasActivatableInterface *iface)
 {
-	iface->activate = pluma_bookmarks_plugin_activate;
-	iface->deactivate = pluma_bookmarks_plugin_deactivate;
+	iface->activate     = pluma_bookmarks_plugin_activate;
+	iface->deactivate   = pluma_bookmarks_plugin_deactivate;
 	iface->update_state = pluma_bookmarks_plugin_update_state;
 }
 
```

**Comment by mbkma** [comment]
@rbuj thanks, done

**Review by rbuj — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
Sorry, I missed this PR from this repo again.
No notification....

**Pull request merged**
