### PR TITLE
update help

### PR DESCRIPTION
**Pull request by raveit65**
and adds synctex help file.

Do not merge before https://github.com/mate-desktop/atril/pull/518 because synctex.page cross-references to atrils help page about synctex.

btw @raveit65 the synctex plugin is used for working with .tex files. More specifically you can work with pluma and atril on .tex files and jump between the source in pluma and the pdf in atril (in atril the shortcut is ctrl+click). See below:
Peek 2021-03-12 12-33

### CODE REVIEW

**Comment by raveit65** [comment]
Opps, you're working already to fix the merge conflict.
I hope i didn't make any mistake with latest force-push.

**Comment by mbkma** [comment]
np, should be fine

**Comment by raveit65** [comment]
Do you see the syntex plugin in yelp?
Bildschirmfoto zu 2021-03-30 10-29-29
The syntex help is installed but i don't see them in yelp.
```
[root@mother rave]# ls -l /usr/share/help/de/pluma-plugins
insgesamt 40
-rw-r--r--  1 root root 2107 30. Mär 10:24 bookmarks.page
-rw-r--r--  1 root root 1179 30. Mär 10:24 bracketcompletion.page
-rw-r--r--. 1 root root 2809 18. Nov 12:46 code-comment.page
-rw-r--r--  1 root root 2003 30. Mär 10:24 codecomment.page
drwxr-xr-x  2 root root 4096 30. Mär 10:24 figures
-rw-r--r--  1 root root 1279 30. Mär 10:24 index.page
-rw-r--r--  1 root root  551 30. Mär 10:24 legal-plugins.xml
-rw-r--r--  1 root root 2123 30. Mär 10:24 synctex.page
-rw-r--r--  1 root root 1855 30. Mär 10:24 terminal.page
-rw-r--r--  1 root root 1969 30. Mär 10:24 wordcompletion.page
```

**Comment by raveit65** [comment]
Ok, pluma help (docbook) and pluma-plugins help are different and not connected.
`yelp /usr/share/help/de/pluma-plugins/synctex.page` is working fine.

**Comment by mbkma** [comment]
Yes, I think pluma-help should be updated from docbook to mallard as in https://github.com/mate-desktop/atril/pull/519 to be able to show pluma-plugins help in pluma help.
You can also see all pluma-plugin help files if you click `menu->All Help->Pluma Plugins` in any of the help dialogues.

**Comment by raveit65** [comment]
I didn't know to choose  the way with `all help`. This works.
Any way, pluma help needs to be rewrite.
I don't think that we can replace the pluma help with gedit help because of different context.

**Review by raveit65 — COMMENTED** [review]
LGTM

**Pull request merged**
