### PR TITLE
Delete unused imports

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by mbkma — APPROVED** [review]
Thanks, this works well. Unused imports are removed and some minor indent/style corrections are done.
You could rename the commits to
`terminal-plugin: Delete unused imports`
and
`codecomment-plugin: Delete unused imports`
respectively for a nicer commit history though.
Btw nice pluma-plugins in your repository, do you mind if I mention them in the mate-wiki at some point?

**Review by mbkma — COMMENTED** [review]
Could you remove the unused imports from the synctex plugin as well, please?

**Comment by ghost** [comment]
@mbkma Thanks. I don't mind if you mention my plug repo on the MATE wiki.

**Comment by mbkma** [comment]
@fszymanski perfect!
Now you can sqash the last commit in the previous and reword the first two commits as suggested. You'll need the `git rebase -i HEAD~4` command (see https://docs.github.com/en/get-started/using-git/using-git-rebase-on-the-command-line for details).

**Review by mbkma — APPROVED** [review]
LGTM

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
