### PR TITLE
Port all plugins to use the window-construct property

### PR DESCRIPTION
**Pull request by mbkma**
related https://github.com/mate-desktop/pluma/pull/617

### CODE REVIEW

**Comment by raveit65** [comment]
Rebased with master to build with pluma-1.25.2.

**Comment by raveit65** [comment]
Do we depend on libpeas after that commit?
https://github.com/mate-desktop/pluma-plugins/blob/master/configure.ac#L56

**Comment by rbuj** [comment]
https://github.com/mate-desktop/pluma-plugins/blob/b873b57cbdcd711d56e579353eef90d369a44efe/plugins/bookmarks/pluma-bookmarks-plugin.c#L109

**Review by raveit65 — APPROVED** [review]
LGTM

**Review by rbuj — APPROVED** [review]
All plugins work properly.

**Pull request merged**
