### PR TITLE
use gi.require_version(), remove double import

### PR DESCRIPTION
**Pull request by mbkma**

### CODE REVIEW

**Comment by rbuj** [comment]
You can split the changes performed in several commits for improving the tracking of the code

**Review by raveit65 — APPROVED** [review]
LGTM,
pluma runs fine when the plugin is enabled.

**Comment by raveit65** [comment]
Well, i don't really know how to use the plugin :)

**Comment by rbuj** [comment]
Test:
1. Open a tex file in pluma
2. Open its pdf output file in atril
3. Press Control+Click anywhere in the document on pluma

Note: both files should be located on the same folder.

Console output
```
 Traceback (most recent call last):
  File "/usr/lib64/pluma/plugins/synctex/synctex.py", line 118, in on_button_release
    self.sync_view(event.time)
  File "/usr/lib64/pluma/plugins/synctex/synctex.py", line 209, in sync_view
    self.window_proxy.SyncView(self.gfile.get_path(), (line, col), time)
  File "/usr/lib64/pluma/plugins/synctex/atril_dbus.py", line 126, in SyncView
    self.window.SyncView(input_file, data, time,  dbus_interface = "org.mate.atril.Window")
  File "/usr/lib64/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method SyncView is not implemented on interface org.mate.atril.Window
```

Sample files: [sample.tar.gz](https://github.com/mate-desktop/pluma-plugins/files/6136960/sample.tar.gz)
- sample.tex (https://guides.nyu.edu/LaTeX/sample-document)
- sample.pdf (pdflatex sample.tex)

**Comment by raveit65** [comment]
I think i will make a first release today without the 2 remaining PRs.
Than i can build a RPM which is better for testing, for me....

**Comment by mbkma** [comment]
@raveit65 I have no time today, but tomorrow I could write a small patch to fix this issue. If the issue mentioned by @rbuj exists in this PR it probably exists in master too. So maybe it is better to temporarily disable the synctex plugin if you need to do a release today.

**Comment by raveit65** [comment]
Np, 1.25.0 is only a developer release. Not much people using developer releases from us. The next major stable release will be 1.26.0.
But  honestly the 1.24 release was a long and lonely run about 4 months for me (only release notes was done by other team members).
I decided not to do this again for me, without a clear defined work-sharing by the team.

**Comment by mbkma** [comment]
@rbuj I could not reproduce the issue, did you compile Atril with synctex support enabled?

**Comment by rbuj** [comment]
@mbkma You're right. I'm sorry. I forgot I disabled the synctex support on atril:
```
Configure summary:
<cut>
    Synctex enabled.....:    no
<cut>
Now type `make' to compile atril
```

**Comment by raveit65** [comment]
@rbuj 
Did you change back the link of gh-pages to pluma-plugins.mate-desktop.dev?
This DNS record won't work because mate-desktop.dev is in the hand of yetist and he needs to add the new sub domain first.
We can use https://mate-desktop.github.io/pluma-plugins/
I edit the cname several times to mate-desktop.github.io/pluma-plugins/, but for some reasons the old none working link is there again after a day.

**Comment by lukefromdc** [comment]
Puma or Pluma? That looks like a typo

On 3/15/2021 at 12:49 PM, "raveit65" ***@***.***> wrote:
>
***@***.***

**Comment by raveit65** [comment]
Yes, it was a typo by me. But the question is the same :)

**Comment by rbuj** [comment]
> @rbuj
> Did you change back the link of gh-pages to pluma-plugins.mate-desktop.dev?

No, I didn't.

**Review by rbuj — APPROVED** [review]
LGTM

**Pull request merged**
