### PR TITLE
configure: conditional AC_CONFIG_FILES

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by mbkma — COMMENTED** [review]
I get the following error:
`make[3]: *** No rule to make target '../plugins/synctex/synctex.plugin.desktop.in', needed by 'pluma-plugins.pot-update'.  Stop.`

with configuration:
```make
Configuration:

	Source code location:   .
	Compiler:               gcc
	Prefix:                 /usr/local
	Python Plugins Support: yes

	Plugins:
	  bookmarks codecomment

	Disabled plugins:
	   synctex (dbus-python not found) terminal (vte not found)
```

**Comment by rbuj** [comment]
@mbkma done

**Comment by rbuj** [comment]
Test:
```
./autogen.sh
rm -f po/pluma-plugins.pot
make -C po pluma-plugins.pot 
grep -F "desktop.in.in" -A 2 po/pluma-plugins.pot 
```

**Comment by mbkma** [comment]
Why do we have ` *.plugin.desktop.in.in` files? In pluma there are only `*.plugin.desktop.in` files. Also in pluma the `*.plugin.desktop.in` files are not listed under AC_CONFIG_FILES in `configure.ac` whereas in pluma-plugins they are. Is there a difference?

**Comment by rbuj** [comment]
### *.plugin
autoconf takes *.plugin.desktop.in.in and writes *.plugin.desktop.in replacing configuration variables like `@VERSION@`. The *.plugin.desktop.in files are listed in `AC_CONFIG_FILES` section of configure.ac file.

The make all target will run the *.plugin targets which require the already created *.plugin.desktop.in files. A .plugin file is built from a .plugin.desktop.in file by adding the translations for name and description entries, The translations comes from the .po files.

### pluma-plugins.pot

```
make -C po pluma-plugins.pot
````
The translations are fetched from *.plugin.desktop.in.in files, as there is no .loc file that binds the file type with a specific file format (the .its file defines the specific rules for extracting the strings) gettext treats them as desktop files, which is the default file format for .desktop.in files.

gettext takes the strings from the files listed in the `POTFILES.in` file. In the translation catalog it does not matter where the translations come from, it’s just a comment on the file.

**Comment by mbkma** [comment]
Ah ok thanks very much for the good explanation! So basically the advantage of using `*.desktop.in.in` instead of `*.desktop.in` files (as in pluma) is, that you can define variables (like @Version@) which will get substituted?

**Review by mbkma — APPROVED** [review]
This works well, the (Make/Desktop/Gschema)files for `synctex` and `terminal` are now only being created if the plugins are enabled (i.e. if the required libs are installed).

**Review by raveit65 — APPROVED** [review]
Distcheck runs successful

**Pull request merged**
