### PR TITLE
add multiedit plugin

### LINKED ISSUE #244: Wishlist: multiple cursor support
GNOME Builder recently got support for [multiple cursors](https://git.gnome.org/browse/gnome-builder/commit/?id=057b61912d882b015d3dd0ffbe6c5616858083fc). This is something I miss a lot when using Pluma instead of Sublime Text. Other editors like KDE's Kate are working on this feature too.

I'm posting this wishlist item so I can post a bounty on it for someone ambitious 😀

### PR DESCRIPTION
**Pull request by mbkma**
Ported from https://gitlab.gnome.org/GNOME/gedit-plugins
Do not merge before https://github.com/mate-desktop/pluma/pull/615
Fixes https://github.com/mate-desktop/pluma/issues/244

### CODE REVIEW

**Review by rbuj — COMMENTED** [review]
Failed to enable multiedit plugin:
```

** (pluma:23339): WARNING **: 09:38:04.602: Error importing plugin 'multiedit':
Traceback (most recent call last):
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'multiedit'

(pluma:23339): libpeas-WARNING **: 09:38:04.602: Error loading plugin 'multiedit'
```
Screenshot at 2021-02-19 09-39-02

**Comment by mbkma** [comment]
You need to build pluma with the new interfaces, see https://github.com/mate-desktop/pluma/pull/615
Edit: The ModuleNotFoundError should be fixed now.

**Comment by raveit65** [comment]
Just rebased with master to use travis-CI.

**Comment by raveit65** [comment]
We have a build error.
```
make[3]: *** No rule to make target '../plugins/multiedit/windowactivatable.py', needed by 'pluma-plugins.pot-update'.  Stop.

make[3]: Leaving directory '/rootdir/po'

make[2]: *** [Makefile:320: pluma-plugins.pot] Error 2

make[2]: Leaving directory '/rootdir/po'

make[1]: *** [Makefile:479: all-recursive] Error 1

make[1]: Leaving directory '/rootdir'

make: *** [Makefile:411: all] Error 2
```
https://travis-ci.org/github/mate-desktop/pluma-plugins/jobs/761038620#L964

**Comment by rbuj** [comment]
I can't enable the plugin. See https://github.com/mate-desktop/pluma-plugins/pull/8#pullrequestreview-593968816

Test:

```
$ cat ~/make.sh 
#!/bin/bash
export LANG=en_US.UFT-8

NPROC=`nproc`
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter -Wdiscarded-qualifiers"
CONF="--prefix=/usr --enable-compile-warnings=maximum --disable-debug"
CFLAGS="${CFLAGS}" ./autogen.sh ${CONF} &> conf.log && make -j${NPROC} &> make.log && sudo make install &> /dev/null
```
```
$ cat ~/bootstrap.sh
#!/bin/bash
export LANG=en_US.UTF-8

git submodule init
git submodule update --recursive --remote
```
```
$ cd
$ git clone git@github.com:mate-desktop/pluma.git
$ cd pluma
$ git checkout activatable
$ sh ~/bootstrap.sh 
$ sh ~/make.sh
$ cd
$ git clone git@github.com:mate-desktop/pluma-plugins.git
$ cd pluma-plugins
$ git checkout multiedit
$ sh ../make.sh
```

**Comment by raveit65** [comment]
> You need to build pluma with the new interfaces, see mate-desktop/pluma#615

Do we need this pluma commit for building pluma-plugins?
Or only for runtime?

**Comment by mbkma** [comment]
For plugins written in C https://github.com/mate-desktop/pluma/pull/615 is needed at compile time because the new interfaces need to be imported, see https://github.com/mate-desktop/pluma-plugins/pull/6#issuecomment-788682929. For python plugins it is needed at runtime.

**Comment by raveit65** [comment]
Ok, than i need to update travis config first.

**Comment by raveit65** [comment]
Rebased with master to build with pluma-1.25.2.

**Comment by raveit65** [comment]
@mbkma @rbuj I removed custom DNS record for cppcheck and clang results. They are now here with github dns https://mate-desktop.github.io/pluma-plugins/
For new PRs this will link will added and used. For existing PRs you need to execute the link by hand.
The DNS record mate-desktop.dev is owned by @yetist  and i think he needs to add pluma-plugins.mate-desktop.dev to his DNS entries
But i didn't hear anything from him for a long time. I hope he is alright behind the great wall.

**Comment by raveit65** [comment]
We have a file conflict with master.

**Comment by raveit65** [comment]
We have a file conflict with master.

**Comment by mbkma** [comment]
I do not think this is a useful plugin. After some time of testing it is either buggy or I do not understand how to use it correctly. If someone urgently needs this plugin, this PR can be reopened.

**Pull request closed without merging**
