### PR TITLE
build: port to gtksourceview-4

### PR DESCRIPTION
**Pull request by rbuj**
Requires https://github.com/mate-desktop/pluma/pull/619

### CODE REVIEW

**Comment by raveit65** [comment]
https://travis-ci.org/github/mate-desktop/pluma-plugins/jobs/760968898#L836
`Package 'gtksourceview-3.0', required by 'pluma', not found`
Fedora build is stable but debian/ubuntu failed.
I think we need to update pluma itself first.

**Comment by raveit65** [comment]
Rebased with master to build with pluma-1.25.2.

**Comment by raveit65** [comment]
Same as before, building failed.

**Comment by rbuj** [comment]
It just needs a new version of pluma with mate-desktop/pluma#619 
https://github.com/mate-desktop/pluma-plugins/blob/c44bb6fe00bbd489f9961fff2a826007a0fec9ab/.build.yml#L102-L104

**Comment by raveit65** [comment]
Really :)
I released yesterday late 1.25.2
Ok , than we need first review https://github.com/mate-desktop/pluma/pull/619

**Comment by raveit65** [comment]
pluma-1.25.3 is released. But i can't add it to travis config because pluma requires gtksourceview-4
 and pluma-plugin (master) requires gtksourceview-3.
So you need to update travis config with this PR.

**Comment by raveit65** [comment]
Ok, it's done.

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
