### PR TITLE
travis: add config for this repo

### PR DESCRIPTION
**Pull request by raveit65**
For some reasons ubuntu build failed but debian is successful.
Here i need a bit help because i am not very familiar with packages in ubuntu/debian.
```
Making all in bookmarks

make[3]: Entering directory '/rootdir/plugins/bookmarks'

  CC       pluma-bookmarks-plugin.lo

  GEN      pluma-bookmarks.metainfo.xml

/usr/bin/msgfmt: cannot locate ITS rules for pluma-bookmarks.metainfo.xml.in

make[3]: *** [Makefile:805: pluma-bookmarks.metainfo.xml] Error 1

make[3]: *** Waiting for unfinished jobs....
```
https://travis-ci.org/github/mate-desktop/pluma-plugins/jobs/760842122#L1413

### CODE REVIEW

**Comment by rbuj** [comment]
Try to set `GETTEXTDATADIR` for locating `its` rules:
```diff 
diff --git a/plugins/bookmarks/Makefile.am b/plugins/bookmarks/Makefile.am
index 002bb67..88fe16d 100644
--- a/plugins/bookmarks/Makefile.am
+++ b/plugins/bookmarks/Makefile.am
@@ -26,7 +26,7 @@ metainfo_DATA = pluma-bookmarks.metainfo.xml
 metainfo_in_files = $(metainfo_DATA:=.in)
 
 $(metainfo_DATA): $(metainfo_in_files)
-       $(AM_V_GEN) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
+       $(AM_V_GEN) GETTEXTDATADIR=$(top_srcdir) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
 
 EXTRA_DIST = \
        $(metainfo_in_files:=.in) \
diff --git a/plugins/codecomment/Makefile.am b/plugins/codecomment/Makefile.am
index 1c83b66..9559a05 100644
--- a/plugins/codecomment/Makefile.am
+++ b/plugins/codecomment/Makefile.am
@@ -14,7 +14,7 @@ metainfo_DATA = pluma-codecomment.metainfo.xml
 metainfo_in_files = $(metainfo_DATA:=.in)
 
 $(metainfo_DATA): $(metainfo_in_files)
-       $(AM_V_GEN) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
+       $(AM_V_GEN) GETTEXTDATADIR=$(top_srcdir) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
 
 EXTRA_DIST = \
        $(metainfo_in_files:=.in) \
diff --git a/plugins/synctex/Makefile.am b/plugins/synctex/Makefile.am
index b53fb74..472b6da 100644
--- a/plugins/synctex/Makefile.am
+++ b/plugins/synctex/Makefile.am
@@ -13,7 +13,7 @@ metainfo_DATA = pluma-synctex.metainfo.xml
 metainfo_in_files = $(metainfo_DATA:=.in)
 
 $(metainfo_DATA): $(metainfo_in_files)
-       $(AM_V_GEN) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
+       $(AM_V_GEN) GETTEXTDATADIR=$(top_srcdir) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
 
 EXTRA_DIST = \
        $(metainfo_in_files:=.in) \
diff --git a/plugins/terminal/Makefile.am b/plugins/terminal/Makefile.am
index 6779cec..17a84d3 100644
--- a/plugins/terminal/Makefile.am
+++ b/plugins/terminal/Makefile.am
@@ -15,7 +15,7 @@ metainfo_DATA = pluma-terminal.metainfo.xml
 metainfo_in_files = $(metainfo_DATA:=.in)
 
 $(metainfo_DATA): $(metainfo_in_files)
-       $(AM_V_GEN) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
+       $(AM_V_GEN) GETTEXTDATADIR=$(top_srcdir) $(MSGFMT) --xml --template $< -d $(top_srcdir)/po -o $@
 
 terminal_gschema_in = org.mate.pluma.plugins.terminal.gschema.xml.in
 gsettings_SCHEMAS = $(terminal_gschema_in:.xml.in=.xml)
```

**Comment by raveit65** [comment]
Now, all builds are failing :/
https://travis-ci.org/github/mate-desktop/pluma-plugins/builds/760848141
I will revert this.

**Comment by rbuj** [comment]
Ok, there is no need to ship the custom its rules for metainfo.xml files since they are already provided by gettext:
You can remove the its rules for .metainfo.xml see #11

**Comment by raveit65** [comment]
Can you add this commit here please?
Than we see if it helps for ubuntu.
But i am still wondering that compiling works for debian-testing but not for ubuntu 20-10 (rolling tag), because usually they use the same build dependencies. But maybe there is a dependency missing for ubuntu.
https://github.com/mate-desktop/pluma-plugins/pull/10/commits/98307239d6aac84efddfbb0fb1098c4c94fb4418#diff-1b49d07a7a51db9ce75c25746b705c396884653384129e0f4cbbd35f3ac9c929R55
Can someone check this who use ubuntu?

**Comment by mbkma** [comment]
@raveit65 If I remember correctly on Debian 10 I needed to install `appstream` for this. Maybe it is the same on Ubuntu.
https://www.freedesktop.org/wiki/Distributions/AppStream/

**Comment by raveit65** [comment]
I don't see `appstream` as dependency in successful debian build log. https://travis-ci.org/github/mate-desktop/pluma-plugins/jobs/760843587
But which one should i add for testing?
```
appstream (0.12.11-1)
    Software component metadata management
appstream-generator (0.8.2-2build1) [universe]
    Generator for AppStream metadata
appstream-index
    virtuelles Paket, bereitgestellt durch appstream
appstream-util (0.7.17-1) [universe]
```
https://packages.ubuntu.com/groovy/allpackages
Edit:
Or maybe these?
```
gir1.2-appstream-1.0 (0.12.11-1)
    Library to access AppStream services (introspection data)
gir1.2-appstreamglib-1.0 (0.7.17-1) [universe]
    GObject introspection data for the libappstream-glib library

libappstream-dev (0.12.11-1)
    Library to access AppStream services (development files)
libappstream-glib-dev (0.7.17-1) [universe]
    GNOME library to access AppStream services (development files)
libappstream-glib8 (0.7.17-1) [universe]
    GNOME library to access AppStream services
libappstream4 (0.12.11-1)
    Library to access AppStream services
```
Sorry, i never used pluma-plugins in result i am not familiar with it.

**Comment by rbuj** [comment]
I also updated the loc file, which contains the pattern to filter the files based on the extension.
```
$ cp /usr/share/gettext-0.21/its/metainfo.loc its/
```
It also includes the rule for detecting AppData files, which is not used at the moment.

**Comment by raveit65** [comment]
Now it builds fine.
@rbuj @mbkma 
Any concerns left or should i merge it?

**Comment by rbuj** [comment]
I can't access to https://pluma-plugins.mate-desktop.dev

https://github.com/mate-desktop/pluma-plugins/blob/32c8c84ff17538baaeadef81d506106e639c15f1/CNAME#L1

https://github.com/mate-desktop/pluma-plugins/deployments/activity_log?environment=github-pages

**Review by rbuj — APPROVED** [review]
LGTM

**Review by mbkma — APPROVED** [review]
builds & runs fine

**Comment by raveit65** [comment]
It can take about 24 hours until Domain's DNS record is available, see https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Pull request merged**
