### PR TITLE
add bracketcompletion plugin

### PR DESCRIPTION
**Pull request by mbkma**
Ported from https://gitlab.gnome.org/GNOME/gedit-plugins
Do not merge before https://github.com/mate-desktop/pluma/pull/615

### CODE REVIEW

**Comment by raveit65** [comment]
Just rebased with master to use travis-CI.

**Comment by raveit65** [comment]
Build error
```
make[2]: *** No rule to make target 'C/bracketcompletion.page', needed by 'all'.  Stop.

make[2]: Leaving directory '/rootdir/help'

make[1]: *** [Makefile:479: all-recursive] Error 1
```
https://travis-ci.org/github/mate-desktop/pluma-plugins/jobs/761038428#L1414

**Comment by raveit65** [comment]
Rebased with master to build with pluma-1.25.2.

**Review by rbuj — APPROVED** [review]
LGTM

**Review by raveit65 — APPROVED** [review]
Does what it promise, very useful module :)

**Pull request merged**
